version: '3.3'
services:
    app:
        build:
            context: ./dockerfiles/app
            args:
            - USERID
            - GROUPID
        container_name: simplecms-app
        volumes:
        - "../../:/var/www/project:cached"
        working_dir: /var/www/project
        env_file:
        - ../../.env
        ports:
        - "8000:8000"
    db:
        image: postgres:12.1-alpine
        container_name: simplecms-db
        ports:
        - "5432:5432"
