doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '12.1'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            SimpleCms:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Blog/Infra/Resources/config/doctrine-mapping'
                prefix: 'SimpleCms\Blog\Domain'
