framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                - validation
            query_bus:
                middleware:
                - validation
